hi TabColor  ctermfg=DarkGray

" vim basic settings

set nu
set autoindent
set tabstop=8
" set shiftwidth=2
set noerrorbells
set background=dark
set si

set list
set listchars=tab:>-
match TabColor /\t/

syntax enable
filetype plugin indent on

" syntax color scheme

let g:solarized_termcolors=256
packadd! dracula
colorscheme dracula

" airline
let g:airline#extensions#tabline#enabled = 1

" airline font and symbols
set guifont=Droid\ Sans\ Mono\ for\ Powerline
let g:Powerline_symbols = 'fancy'
let g:airline_powerline_fonts = 1

map <C-S><left> :tabp<cr>
map <C-S><right> :tabn<cr>

command Html read ~/.vim/templates/html
